export const socios = [
    {
        nombre:'Tableau',
        imgUrl:'tableau-partner.png',
        pageUrl:'https://www.tableau.com/es-mx'
    },
    {
        nombre:'Salesforce',
        imgUrl:'salesforce.jpg',
        pageUrl:'https://www.salesforce.com/mx/'
    },
    {
        nombre:'Dell',
        imgUrl:'dell.png',
        pageUrl:'https://www.dell.com/en-us'
    },
    {
        nombre:'Hp',
        imgUrl:'hp.png',
        pageUrl:'https://www.hp.com/mx-es/home.html'
    },
    {
        nombre:'Tableau',
        imgUrl:'tableau-partner.png',
        pageUrl:'https://www.tableau.com/es-mx'
    },
    {
        nombre:'Red Hat',
        imgUrl:'redhat.png',
        pageUrl:'https://www.redhat.com/en'
    },
    {
        nombre:'Microsoft',
        imgUrl:'microsoft.png',
        pageUrl:'https://www.microsoft.com/es-mx/'
    },
    {
        nombre:'Kaspersky',
        imgUrl:'kaspersky.png',
        pageUrl:'https://latam.kaspersky.com/'
    },
    {
        nombre:'IBM',
        imgUrl:'ibm.png',
        pageUrl:'https://www.ibm.com/mx-es'
    }
]